# Generated by Django 4.2.4 on 2023-08-26 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='expeience',
            new_name='experience',
        ),
    ]
